name: primeira-pipeline

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  primeiro-job:
    name: "Meu Primeiro Job"
    runs-on: ubuntu-latest
    steps:
      - name: "Minha primeira ação"
        run: echo "Hello World !!!"

      - name: "Segunda ação"
        run: |
          echo "Você criou o seu primeiro workflow !!!"
          echo "Parabéns !!!"
          
      - name: "Script Python"
        run: |
          variavel = "Hello World !!!"
          print(variavel)
        shell: python
  segundo-job:
    name: "Instalacao do Ambiente NodeJS"
    runs-on: ubuntu-latest
    needs: [primeiro-job]
    steps:
       - name: "Verificacao da versao do NodeJS atual"
         run: node --version
         
       - name: "Definicao da versao v24.3.0 do NodeJS"
         uses: actions/setup-node@v4
         with: 
          node-version: '24.3.0'
          
       - name: "Verificacao da versao do NodeJS atualizado"
         run: node --version
  
